# Generated by Django 5.2.6 on 2025-09-23 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userpreferences", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userpreference",
            old_name="user",
            new_name="owner",
        ),
    ]
