# Generated by Django 5.2.6 on 2025-09-23 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userpreferences", "0002_rename_user_userpreference_owner"),
    ]

    operations = []
