name: Django CI & Error Detection

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint black reviewdog
    - name: Lint Python code
      run: |
        pylint **/*.py | reviewdog -f=pylint -name="pylint" -reporter=github-pr-check -level=error
    - name: Check migrations
      run: |
        python manage.py makemigrations --dry-run --check
        python manage.py migrate --plan
    - name: Run Django tests
      run: |
        python manage.py test | reviewdog -f=pytest -name="Django Tests" -reporter=github-pr-check -level=error
